---
version: 2
updates:

# enable dependabot updates for project dependencies

  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: daily
      time: '5:00'
    target-branch: main

# enable dependabot updates for workflow versions

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '5:00'
    target-branch: main
