name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: build

    - name: Upload debug apk
      uses: actions/upload-artifact@v2
      if: ${{ !github.head_ref }}
      with:
        name: apk-debug
        path: app/build/outputs/apk
